on:
  schedule:
    # Update Tuesdays 6:00am UTC / 1:00am ET
    - cron:  '00 6 * 1-12 2'
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::lubridate
            any::oddsapiR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Key as enviroment variable
        env: # Or as an environment variable
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          echo "$ODDS_API_KEY"
          echo "$ODDS_API_KEY" | sed 's/./& /g'

      #- name: Use Secret in Workflow
      #  run: echo "The API key is ${{ secrets.ODDS_API_KEY }}"

      - name: Update Super Bowl Odds
        run: Rscript -e 'source("R/sb_odds.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
