on:
  schedule:
    # Update Tuesdays at 10:00am UTC / 4:00am ET
    - cron:  '00 10 * 1-12 2'
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    env: # API Keys must be before steps, and set as env variables
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::lubridate
            any::oddsapiR
            any::readr
            any::RCurl

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Super Bowl Futures
        run: Rscript -e 'source("R/sb_futures.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
